server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/wikitabia
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  sql:
    init:
      schema-locations: classpath:init.sql
      mode: always
